In [13]:
import pandas as pd

data_inputs = "../data/inputs/"

data_santiago = "ventas_santiago.csv"
data_buenos_aires = "ventas_buenos_aires.json"
data_lima = "ventas_lima.parquet"

In [24]:
df_santiago = pd.read_csv(data_inputs + data_santiago)
print("**********Info df santiago**********")
print(df_santiago.info())
print("**********Descripcion df santiago**********")
print(df_santiago.describe())
print("**********Tabla df santiago**********")
df_santiago.head(10)

**********Info df santiago**********
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_transaccion  10000 non-null  object
 1   ciudad          10000 non-null  object
 2   monto           10000 non-null  int64
 3   fecha           10000 non-null  object
dtypes: int64(1), object(3)
memory usage: 312.6+ KB
None
**********Descripcion df santiago**********
               monto
count   10000.000000
mean    61089.845300
std     53902.583181
min    -49976.000000
25%     20990.250000
50%     63696.500000
75%    106998.500000
max    149997.000000
**********Tabla df santiago**********

  id_transaccion        ciudad   monto       fecha
0    STGO-000001      Santiago  -43481  2026-05-12
1    STGO-000002      Santiago  -12734  2026-05-27
2    STGO-000003      Santiago   88332  2026-05-11
3    STGO-000004  Santiago_Err  100349  2026-06-10
4    STGO-000005      Santiago  -17431  2026-06-02
5    STGO-000006  Santiago_Err   18727  2026-05-24
6    STGO-000007      Santiago   34690  2026-05-27
7    STGO-000008      Santiago  109747  2026-05-22
8    STGO-000009   Stgo_Centro  119778  2026-06-01
9    STGO-000010    Valparaiso   89538  2026-05-29

In [25]:
df_buenos_aires = pd.read_json(data_inputs + data_buenos_aires, lines=True)
print("**********Info df Buenos Aires**********")
print(df_buenos_aires.info())
print("**********Descripcion df Buenos Aires**********")
print(df_buenos_aires.describe())
print("**********Tabla df Buenos Aires**********")
df_buenos_aires.head(10)

**********Info df Buenos Aires**********
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   tx_id      10000 non-null  object
 1   sucursal   10000 non-null  object
 2   total      10000 non-null  object
 3   timestamp  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 312.6+ KB
None
**********Descripcion df Buenos Aires**********
                           timestamp
count                          10000
mean   2026-05-25 23:36:05.759999744
min              2026-05-11 00:00:00
25%              2026-05-18 00:00:00
50%              2026-05-26 00:00:00
75%              2026-06-03 00:00:00
max              2026-06-10 00:00:00
**********Tabla df Buenos Aires**********

       tx_id      sucursal         total  timestamp
0  BA-000001  Buenos Aires         82775 2026-06-08
1  BA-000002  Buenos Aires         11902 2026-05-22
2  BA-000003  Buenos Aires         49615 2026-05-21
3  BA-000004  Buenos Aires         19245 2026-06-09
4  BA-000005  Buenos Aires         13094 2026-05-19
5  BA-000006  Buenos Aires  CRITICAL_ERR 2026-05-19
6  BA-000007  BsAs_Erronea          6568 2026-05-12
7  BA-000008  Buenos Aires        -18794 2026-06-10
8  BA-000009  Buenos Aires    NULO_ERROR 2026-06-06
9  BA-000010    Baires_Mal         65861 2026-05-31

In [26]:
df_lima = pd.read_parquet(data_inputs + data_lima, engine="pyarrow")
print("**********Info df lima**********")
print(df_lima.info())
print("**********Descripcion df lima**********")
print(df_lima.describe())
print("**********Tabla df lima**********")
df_lima.head(10)

**********Info df lima**********
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  10000 non-null  object
 1   city            10000 non-null  object
 2   local_value     10000 non-null  float64
 3   sales_date      10000 non-null  object
dtypes: float64(1), object(3)
memory usage: 312.6+ KB
None
**********Descripcion df lima**********
        local_value
count  10000.000000
mean     202.027977
std      176.213256
min     -150.000000
25%       66.357500
50%      208.920000
75%      349.822500
max      499.920000
**********Tabla df lima**********

  transaction_id      city  local_value  sales_date
0    LIMA-000001      Lima       316.70  2026-05-27
1    LIMA-000002    Callao       424.20  2026-06-03
2    LIMA-000003      Lima       -76.52  2026-05-24
3    LIMA-000004      Lima       114.15  2026-06-05
4    LIMA-000005      Lima       462.89  2026-05-18
5    LIMA-000006      Lima       -67.34  2026-05-28
6    LIMA-000007      Lima       -60.90  2026-06-02
7    LIMA-000008  Arequipa       168.32  2026-05-15
8    LIMA-000009      Lima       282.75  2026-05-14
9    LIMA-000010  Arequipa       167.57  2026-06-01

## Observaciones
Las tablas tienen distintos nombres de columnas entre ellas, los nombres correctos son:
- id_transaccion
- ciudad
- monto_original (**debe ser string para capa PSA**)
- moneda_origen (se debe agregar codigo de 3 letras segun pais CLP, ARS, PEN)
- fecha_transaccion (**debe ser string para capa PSA**)
- ingestado_at (timestamp, se debe agregar **debe ser string para capa PSA**)

## Errores y acciones conocidas

- Los nombres de ciudades pueden tener errores o estar male scritos
- La columna de nombre de ciudad puede contener ciudades que no nos competen
- Se deben limpiar espacios en blanco de inicio y fin de string en columna ciudad
- Se deberia llevar todos los nombres de ciudades a minusculas